easy_admin:
    site_name: 'AFTERTECH <em style="font-size: 80%;">. Administration</em>'
    design:
        brand_color: '#8c99e0'
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - entreprise
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        Event:
            class: App\Entity\Event
        Entreprise:
            class: App\Entity\Entreprise
            list:
                fields:
                    - { property: 'nom' }
                    - { property: 'description' }
            form:
                fields:
                    - nom
                    - description
                    - user
        Groupe:
              class: App\Entity\Groupe
              list:
                 fields:
                    - { property: 'nom' }
              form:
                fields:
                    - nom
                    - message