#easy_admin:
#
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\User
#        - App\Entity\Groupe
#        - App\Entity\UserGroupe
#        - App\Entity\Entreprise


easy_admin:
    site_name: 'AfterTech Backend'
    entities:
        User:
            class: App\Entity\User
            form:
              fields:
                  property: 'username'