fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

index:
    path: /
    defaults: { _controller: 'App\Controller\LandingController::indexAction' }

user_connexion:
    path: /connexion
    defaults: { _controller: 'App\Controller\ProfilController::connexionAction' }


profil_add_groupe:
    path: profil/
    defaults: { _controller: 'App\Controller\ProfilController::addGroupeAction' }

groupe_show:
    path: groupe/show
    defaults: { _controller: 'App\Controller\GroupeController::showAction' }

groupe_add:
    path: groupe/add
    defaults: { _controller: 'App\Controller\GroupeController::addAction' }

message_add:
    path: message/add/{groupe}
    defaults: { _controller: 'App\Controller\MessageController::addAction' }

message_insert:
    path: message/insert/{groupe}
    defaults: { _controller: 'App\Controller\MessageController::insertAction' }


event_show:
    path: event/show
    defaults: { _controller: 'App\Controller\EventController::indexAction' }

event_calendar_loader:
    path: event/loadcalendar
    defaults: { _controller: 'App\Controller\CalendarEventController::loadCalendarAction' }
    options:
        expose: true

event_add:
    path: event/add/{groupe}
    defaults: { _controller: 'App\Controller\EventController::addAction' }


user_invite:
    path: user/invite/{groupe}
    defaults: { _controller: 'App\Controller\MessageController::userInviteAction' }

user_invite_notif:
    path: user/invitenotif
    defaults: { _controller: 'App\Controller\NotifController::showAction' }

user_invite_accepte:
    path: user/inviteaccepte/{id}
    defaults: { _controller: 'App\Controller\NotifController::accepterAction' }

entreprise_add:
    path: entreprise/add
    defaults: { _controller: 'App\Controller\EntrepriseController::addAction' }

entreprise_show:
    path: entreprise/show/{id}
    defaults: { _controller: 'App\Controller\EntrepriseController::showAction' }

entreprise_actu_show:
    path: entreprise/actu/show/{id}
    defaults: { _controller: 'App\Controller\EntrepriseController::showActuAction' }





#app_bundle:
    # loads routes from the YAML or XML files found in some bundle directory
    #resource: '@AppBundle/Resources/config/routing/'
    #type:     directory
