fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path: /
    defaults: { _controller: 'App\Controller\LandingController::indexAction' }

user_connexion:
    path: /connexion
    defaults: { _controller: 'App\Controller\ProfilController::connexionAction' }


profil_add_groupe:
    path: profil/
    defaults: { _controller: 'App\Controller\ProfilController::addGroupeAction' }

groupe_show:
    path: groupe/show
    defaults: { _controller: 'App\Controller\GroupeController::showAction' }

groupe_add:
    path: groupe/add
    defaults: { _controller: 'App\Controller\GroupeController::addAction' }

message_add:
    path: message/add
    defaults: { _controller: 'App\Controller\MessageController::addAction' }




#app_bundle:
    # loads routes from the YAML or XML files found in some bundle directory
    #resource: '@AppBundle/Resources/config/routing/'
    #type:     directory
